# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Initial
      run: python -m PyInstaller --onefile --windowed main.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: Application Artifacts
          path: 
            ./dist/**
    
